### ISSUE TITLE
/v1/boards.json not returning pulses

### ISSUE THREAD

**Issue by angeltveit** [leemm/dapulse#1]
According to the documention boards should return pulses, but I can't seem to get them using this plugin. Anything I'm doing wrong?

**Comment by leemm** [comment]
It basically wraps this request:
[https://api.dapulse.com:443/v1/boards.json?api_key=<key>](https://api.dapulse.com:443/v1/boards.json?api_key=<key>)

When I run it against my account the only get these properties in the payload:
```
[
  {
    "url": "https://otrack.dapulse.com/boards/2037123",
    "id": 2037123,
    "name": "Testing",
    "description": "Testing board.",
    "columns": [...],
    "groups": [...],
    "created_at": "2015-06-26T12:02:19Z",
    "updated_at": "2016-11-04T09:37:18Z"
  }
]
```

I don't get an array of pulses either.  Perhaps it's either a bug in the API or incorrect documentation?

**Comment by angeltveit** [comment]
Yes, it seems the endpoint does not return the data as the documentation says it should. So the issue is not with your plugin. Sorry about that.

Anyway, I solved it by also getting /boards/{board_id}/pulses.

**Comment by leemm** [comment]
No problem!  I noticed a few inconsistencies myself when I was putting it together.  Glad you found a work around.
